export type WatchCategory =
  | "smartwatch"
  | "sportwatch"
  | "band"
  | "hybrid";

export type WatchUse = "running" | "multisport" | "outdoor" | "gym" | "everyday" | "health";
export type WatchPhone = "iphone" | "android" | "both";
export type WatchStyle = "minimal" | "rugged" | "luxury" | "sporty";

export interface Watch {
  id: string;
  brand: string;
  model: string;
  year: number;
  category: WatchCategory;
  priceUSD: number;
  /** GPS-on battery hours; for bands without GPS, use everyday hours */
  batteryDays: number;
  caseSizeMM: number;
  weightGrams: number;
  display: "AMOLED" | "OLED" | "LCD" | "MIP" | "E-ink";
  waterRating: string; // e.g. "5ATM", "10ATM", "IP68"
  features: string[]; // tokens matching quiz feature ids
  bestFor: WatchUse[];
  phones: WatchPhone[];
  style: WatchStyle[];
  highlight: string;
  imageURL?: string;
}

/**
 * A curated, manufacturer-spec-checked database of popular smartwatches,
 * sportwatches and fitness bands (2023–2025 line-up).
 */
export const watchDatabase: Watch[] = [
  {
    id: "apple-watch-ultra-2",
    brand: "Apple",
    model: "Watch Ultra 2",
    year: 2024,
    category: "smartwatch",
    priceUSD: 799,
    batteryDays: 1.5,
    caseSizeMM: 49,
    weightGrams: 61,
    display: "AMOLED",
    waterRating: "10ATM",
    features: ["gps", "ecg", "spo2", "music", "lte", "payments", "amoled", "maps", "swim"],
    bestFor: ["multisport", "outdoor", "running", "health"],
    phones: ["iphone"],
    style: ["rugged", "sporty", "luxury"],
    highlight: "Apple's most rugged smartwatch — dive-rated, dual-frequency GPS, 36-hour battery in low-power mode.",
  },
  {
    id: "apple-watch-series-10",
    brand: "Apple",
    model: "Watch Series 10",
    year: 2024,
    category: "smartwatch",
    priceUSD: 399,
    batteryDays: 1.2,
    caseSizeMM: 46,
    weightGrams: 36,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "ecg", "spo2", "music", "payments", "amoled", "swim"],
    bestFor: ["everyday", "health", "gym", "running"],
    phones: ["iphone"],
    style: ["minimal", "luxury", "sporty"],
    highlight: "The all-rounder for iPhone users — thinnest Apple Watch ever, faster charging, full health suite.",
  },
  {
    id: "apple-watch-se-2",
    brand: "Apple",
    model: "Watch SE (2nd gen)",
    year: 2023,
    category: "smartwatch",
    priceUSD: 249,
    batteryDays: 1.2,
    caseSizeMM: 44,
    weightGrams: 33,
    display: "OLED",
    waterRating: "5ATM",
    features: ["gps", "music", "payments", "swim"],
    bestFor: ["everyday", "gym", "running"],
    phones: ["iphone"],
    style: ["minimal", "sporty"],
    highlight: "Best-value Apple Watch — core fitness, calls and Apple Pay without the ECG/SpO2 premium.",
  },
  {
    id: "samsung-galaxy-watch-7",
    brand: "Samsung",
    model: "Galaxy Watch 7",
    year: 2024,
    category: "smartwatch",
    priceUSD: 299,
    batteryDays: 1.5,
    caseSizeMM: 44,
    weightGrams: 34,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "ecg", "spo2", "music", "payments", "amoled", "swim"],
    bestFor: ["everyday", "health", "gym", "running"],
    phones: ["android"],
    style: ["minimal", "sporty"],
    highlight: "The flagship Wear OS smartwatch for Android — body composition, sleep coaching and dual-frequency GPS.",
  },
  {
    id: "samsung-galaxy-watch-ultra",
    brand: "Samsung",
    model: "Galaxy Watch Ultra",
    year: 2024,
    category: "smartwatch",
    priceUSD: 649,
    batteryDays: 2.5,
    caseSizeMM: 47,
    weightGrams: 60,
    display: "AMOLED",
    waterRating: "10ATM",
    features: ["gps", "ecg", "spo2", "music", "lte", "payments", "amoled", "swim"],
    bestFor: ["multisport", "outdoor", "running"],
    phones: ["android"],
    style: ["rugged", "sporty"],
    highlight: "Samsung's adventure flagship — titanium case, 100m water resistance, dual-frequency GPS.",
  },
  {
    id: "google-pixel-watch-3",
    brand: "Google",
    model: "Pixel Watch 3",
    year: 2024,
    category: "smartwatch",
    priceUSD: 349,
    batteryDays: 1,
    caseSizeMM: 45,
    weightGrams: 37,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "ecg", "spo2", "music", "payments", "amoled", "swim"],
    bestFor: ["everyday", "health", "running"],
    phones: ["android"],
    style: ["minimal", "luxury"],
    highlight: "Google's most refined Pixel Watch — Fitbit-powered fitness, gorgeous 320 ppi AMOLED.",
  },
  {
    id: "garmin-fenix-8",
    brand: "Garmin",
    model: "fēnix 8",
    year: 2024,
    category: "sportwatch",
    priceUSD: 1099,
    batteryDays: 16,
    caseSizeMM: 47,
    weightGrams: 73,
    display: "AMOLED",
    waterRating: "10ATM",
    features: ["gps", "spo2", "music", "payments", "amoled", "maps", "swim"],
    bestFor: ["multisport", "outdoor", "running"],
    phones: ["both"],
    style: ["rugged", "luxury"],
    highlight: "Garmin's no-compromise multisport flagship — built-in dive computer, AMOLED, multi-band GPS.",
  },
  {
    id: "garmin-forerunner-965",
    brand: "Garmin",
    model: "Forerunner 965",
    year: 2023,
    category: "sportwatch",
    priceUSD: 599,
    batteryDays: 23,
    caseSizeMM: 47,
    weightGrams: 53,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "spo2", "music", "payments", "amoled", "maps", "swim"],
    bestFor: ["running", "multisport"],
    phones: ["both"],
    style: ["sporty"],
    highlight: "Best AMOLED running watch — full-color maps, training readiness and 23-day everyday battery.",
  },
  {
    id: "garmin-forerunner-265",
    brand: "Garmin",
    model: "Forerunner 265",
    year: 2023,
    category: "sportwatch",
    priceUSD: 449,
    batteryDays: 13,
    caseSizeMM: 46,
    weightGrams: 47,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "spo2", "music", "amoled", "swim"],
    bestFor: ["running", "multisport"],
    phones: ["both"],
    style: ["sporty", "minimal"],
    highlight: "Mid-range runner's pick — bright AMOLED, training load focus, race predictor.",
  },
  {
    id: "garmin-instinct-3",
    brand: "Garmin",
    model: "Instinct 3 Solar",
    year: 2025,
    category: "sportwatch",
    priceUSD: 449,
    batteryDays: 24,
    caseSizeMM: 45,
    weightGrams: 58,
    display: "MIP",
    waterRating: "10ATM",
    features: ["gps", "spo2", "swim"],
    bestFor: ["outdoor", "multisport"],
    phones: ["both"],
    style: ["rugged"],
    highlight: "Solar-charged tank — months of battery, MIL-STD-810 toughness, brilliant always-on MIP screen.",
  },
  {
    id: "garmin-vivoactive-5",
    brand: "Garmin",
    model: "vívoactive 5",
    year: 2023,
    category: "smartwatch",
    priceUSD: 299,
    batteryDays: 11,
    caseSizeMM: 42,
    weightGrams: 36,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "spo2", "music", "payments", "amoled", "swim"],
    bestFor: ["everyday", "gym", "running"],
    phones: ["both"],
    style: ["minimal", "sporty"],
    highlight: "Most accessible Garmin AMOLED — 11-day battery, sleep coach, gym workouts and music storage.",
  },
  {
    id: "coros-pace-3",
    brand: "Coros",
    model: "Pace 3",
    year: 2023,
    category: "sportwatch",
    priceUSD: 229,
    batteryDays: 24,
    caseSizeMM: 42,
    weightGrams: 30,
    display: "MIP",
    waterRating: "5ATM",
    features: ["gps", "music"],
    bestFor: ["running", "multisport"],
    phones: ["both"],
    style: ["minimal", "sporty"],
    highlight: "Ultralight runner's bargain — dual-frequency GPS at 30g, 24-day battery, EvoLab analytics.",
  },
  {
    id: "coros-vertix-2s",
    brand: "Coros",
    model: "Vertix 2S",
    year: 2024,
    category: "sportwatch",
    priceUSD: 699,
    batteryDays: 40,
    caseSizeMM: 50,
    weightGrams: 72,
    display: "MIP",
    waterRating: "10ATM",
    features: ["gps", "spo2", "music", "maps", "swim"],
    bestFor: ["outdoor", "multisport"],
    phones: ["both"],
    style: ["rugged"],
    highlight: "40-day adventure beast — offline global maps, dual-frequency GPS, titanium bezel.",
  },
  {
    id: "polar-vantage-v3",
    brand: "Polar",
    model: "Vantage V3",
    year: 2023,
    category: "sportwatch",
    priceUSD: 599,
    batteryDays: 8,
    caseSizeMM: 47,
    weightGrams: 57,
    display: "AMOLED",
    waterRating: "10ATM",
    features: ["gps", "ecg", "spo2", "amoled", "maps", "swim"],
    bestFor: ["multisport", "running", "health"],
    phones: ["both"],
    style: ["sporty"],
    highlight: "Lab-grade biometrics — ECG, skin-temp, wrist-based hemoglobin, training readiness.",
  },
  {
    id: "suunto-race",
    brand: "Suunto",
    model: "Race",
    year: 2023,
    category: "sportwatch",
    priceUSD: 449,
    batteryDays: 12,
    caseSizeMM: 49,
    weightGrams: 69,
    display: "AMOLED",
    waterRating: "10ATM",
    features: ["gps", "spo2", "amoled", "maps", "swim"],
    bestFor: ["outdoor", "multisport", "running"],
    phones: ["both"],
    style: ["rugged", "sporty"],
    highlight: "Finnish-built dual-frequency GPS with offline maps — rotating crown UI feels great.",
  },
  {
    id: "amazfit-t-rex-3",
    brand: "Amazfit",
    model: "T-Rex 3",
    year: 2024,
    category: "sportwatch",
    priceUSD: 279,
    batteryDays: 27,
    caseSizeMM: 48,
    weightGrams: 68,
    display: "AMOLED",
    waterRating: "10ATM",
    features: ["gps", "spo2", "music", "amoled", "maps", "swim"],
    bestFor: ["outdoor", "multisport"],
    phones: ["both"],
    style: ["rugged"],
    highlight: "Rugged AMOLED at half the price — dual-band GPS, offline maps, 27-day battery.",
  },
  {
    id: "amazfit-bip-5",
    brand: "Amazfit",
    model: "Bip 5 Unity",
    year: 2024,
    category: "smartwatch",
    priceUSD: 99,
    batteryDays: 11,
    caseSizeMM: 46,
    weightGrams: 33,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "spo2", "amoled"],
    bestFor: ["everyday", "gym"],
    phones: ["both"],
    style: ["minimal", "sporty"],
    highlight: "Big AMOLED smartwatch under $100 — surprisingly capable for daily fitness tracking.",
  },
  {
    id: "fitbit-charge-6",
    brand: "Fitbit",
    model: "Charge 6",
    year: 2023,
    category: "band",
    priceUSD: 159,
    batteryDays: 7,
    caseSizeMM: 36,
    weightGrams: 23,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "ecg", "spo2", "payments", "amoled", "swim"],
    bestFor: ["everyday", "health", "gym"],
    phones: ["both"],
    style: ["minimal"],
    highlight: "The most full-featured fitness band — built-in GPS, ECG and Google Maps on the wrist.",
  },
  {
    id: "fitbit-inspire-3",
    brand: "Fitbit",
    model: "Inspire 3",
    year: 2022,
    category: "band",
    priceUSD: 99,
    batteryDays: 10,
    caseSizeMM: 35,
    weightGrams: 19,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["spo2", "amoled"],
    bestFor: ["everyday", "health"],
    phones: ["both"],
    style: ["minimal"],
    highlight: "Featherlight wellness band — sleep score, stress and active zone minutes.",
  },
  {
    id: "xiaomi-smart-band-9",
    brand: "Xiaomi",
    model: "Smart Band 9",
    year: 2024,
    category: "band",
    priceUSD: 49,
    batteryDays: 21,
    caseSizeMM: 47,
    weightGrams: 16,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["spo2", "amoled"],
    bestFor: ["everyday"],
    phones: ["both"],
    style: ["minimal"],
    highlight: "21-day battery in a $50 AMOLED band — unbeatable wellness tracker for the price.",
  },
  {
    id: "huawei-watch-gt-5-pro",
    brand: "Huawei",
    model: "Watch GT 5 Pro",
    year: 2024,
    category: "smartwatch",
    priceUSD: 379,
    batteryDays: 14,
    caseSizeMM: 46,
    weightGrams: 53,
    display: "AMOLED",
    waterRating: "10ATM",
    features: ["gps", "ecg", "spo2", "music", "amoled", "maps", "swim"],
    bestFor: ["everyday", "outdoor", "health"],
    phones: ["both"],
    style: ["luxury", "sporty"],
    highlight: "Two-week battery in a titanium-and-sapphire luxury smartwatch.",
  },
  {
    id: "withings-scanwatch-2",
    brand: "Withings",
    model: "ScanWatch 2",
    year: 2023,
    category: "hybrid",
    priceUSD: 349,
    batteryDays: 30,
    caseSizeMM: 42,
    weightGrams: 53,
    display: "OLED",
    waterRating: "5ATM",
    features: ["ecg", "spo2", "swim"],
    bestFor: ["health", "everyday"],
    phones: ["both"],
    style: ["luxury", "minimal"],
    highlight: "Analog hybrid with medical-grade ECG and 30-day battery — looks like a real watch.",
  },
  {
    id: "whoop-4",
    brand: "Whoop",
    model: "4.0",
    year: 2023,
    category: "band",
    priceUSD: 239,
    batteryDays: 5,
    caseSizeMM: 32,
    weightGrams: 27,
    display: "E-ink",
    waterRating: "10ATM",
    features: ["spo2"],
    bestFor: ["health", "gym", "running"],
    phones: ["both"],
    style: ["minimal"],
    highlight: "Screen-free recovery and strain coaching — the choice of pro athletes (subscription required).",
  },
  {
    id: "mobvoi-ticwatch-pro-5",
    brand: "Mobvoi",
    model: "TicWatch Pro 5",
    year: 2023,
    category: "smartwatch",
    priceUSD: 349,
    batteryDays: 3,
    caseSizeMM: 50,
    weightGrams: 44,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "spo2", "payments", "amoled", "swim"],
    bestFor: ["everyday", "gym", "running"],
    phones: ["android"],
    style: ["sporty", "rugged"],
    highlight: "Dual-display Wear OS watch — premium chip and 80-hour standby thanks to its low-power overlay.",
  },
];

export function getWatchById(id: string): Watch | undefined {
  return watchDatabase.find((w) => w.id === id);
}

export const WATCH_DB_LAST_UPDATED = "May 2026";