export type WatchCategory =
  | "smartwatch"
  | "sportwatch"
  | "band"
  | "hybrid";

export type WatchUse = "running" | "multisport" | "outdoor" | "gym" | "everyday" | "health";
export type WatchPhone = "iphone" | "android" | "both";
export type WatchStyle = "minimal" | "rugged" | "luxury" | "sporty";

export interface Watch {
  id: string;
  brand: string;
  model: string;
  year: number;
  category: WatchCategory;
  priceUSD: number;
  /** GPS-on battery hours; for bands without GPS, use everyday hours */
  batteryDays: number;
  caseSizeMM: number;
  weightGrams: number;
  display: "AMOLED" | "OLED" | "LCD" | "MIP" | "E-ink";
  waterRating: string; // e.g. "5ATM", "10ATM", "IP68"
  features: string[]; // tokens matching quiz feature ids
  bestFor: WatchUse[];
  phones: WatchPhone[];
  style: WatchStyle[];
  highlight: string;
  /** Verified Amazon Standard Identification Number — when present, deep-links straight to the product page. */
  asin?: string;
  /** Path on gearuptofit.com (without leading slash) for the in-depth review article. */
  reviewPath?: string;
  imageURL?: string;
}

/**
 * A curated, manufacturer-spec-checked database of popular smartwatches,
 * sportwatches and fitness bands (2023–2025 line-up).
 */
export const watchDatabase: Watch[] = [
  {
    id: "apple-watch-ultra-2",
    brand: "Apple",
    model: "Watch Ultra 2",
    year: 2024,
    category: "smartwatch",
    priceUSD: 799,
    batteryDays: 1.5,
    caseSizeMM: 49,
    weightGrams: 61,
    display: "AMOLED",
    waterRating: "10ATM",
    features: ["gps", "ecg", "spo2", "music", "lte", "payments", "amoled", "maps", "swim"],
    bestFor: ["multisport", "outdoor", "running", "health"],
    phones: ["iphone"],
    style: ["rugged", "sporty", "luxury"],
    highlight: "Apple's most rugged smartwatch — dive-rated, dual-frequency GPS, 36-hour battery in low-power mode.",
    asin: "B0CSVG2GM8",
    reviewPath: "review/apple-watch-ultra-2",
    imageURL: "https://m.media-amazon.com/images/I/81D7OmeXqoL._AC_SL1500_.jpg"
  },
  {
    id: "apple-watch-series-10",
    brand: "Apple",
    model: "Watch Series 10",
    year: 2024,
    category: "smartwatch",
    priceUSD: 399,
    batteryDays: 1.2,
    caseSizeMM: 46,
    weightGrams: 36,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "ecg", "spo2", "music", "payments", "amoled", "swim"],
    bestFor: ["everyday", "health", "gym", "running"],
    phones: ["iphone"],
    style: ["minimal", "luxury", "sporty"],
    highlight: "The all-rounder for iPhone users — thinnest Apple Watch ever, faster charging, full health suite.",
    asin: "B0DGHQ2QH6",
    reviewPath: "review/apple-watch-series-10",
    imageURL: "https://m.media-amazon.com/images/I/61bJZx1v8GL._AC_SL1500_.jpg"
  },
  {
    id: "apple-watch-se-2",
    brand: "Apple",
    model: "Watch SE (2nd gen)",
    year: 2023,
    category: "smartwatch",
    priceUSD: 249,
    batteryDays: 1.2,
    caseSizeMM: 44,
    weightGrams: 33,
    display: "OLED",
    waterRating: "5ATM",
    features: ["gps", "music", "payments", "swim"],
    bestFor: ["everyday", "gym", "running"],
    phones: ["iphone"],
    style: ["minimal", "sporty"],
    highlight: "Best-value Apple Watch — core fitness, calls and Apple Pay without the ECG/SpO2 premium.",
    asin: "B0DGJ736JM",
    imageURL: "https://m.media-amazon.com/images/I/61ZTaGRrabL._AC_SL1500_.jpg"
  },
  {
    id: "samsung-galaxy-watch-7",
    brand: "Samsung",
    model: "Galaxy Watch 7",
    year: 2024,
    category: "smartwatch",
    priceUSD: 299,
    batteryDays: 1.5,
    caseSizeMM: 44,
    weightGrams: 34,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "ecg", "spo2", "music", "payments", "amoled", "swim"],
    bestFor: ["everyday", "health", "gym", "running"],
    phones: ["android"],
    style: ["minimal", "sporty"],
    highlight: "The flagship Wear OS smartwatch for Android — body composition, sleep coaching and dual-frequency GPS.",
    asin: "B0D7JZ51LW",
    reviewPath: "review/samsung-galaxy-watch-7",
    imageURL: "https://m.media-amazon.com/images/I/61SQBMBnlhL._AC_SL1500_.jpg"
  },
  {
    id: "samsung-galaxy-watch-ultra",
    brand: "Samsung",
    model: "Galaxy Watch Ultra",
    year: 2024,
    category: "smartwatch",
    priceUSD: 649,
    batteryDays: 2.5,
    caseSizeMM: 47,
    weightGrams: 60,
    display: "AMOLED",
    waterRating: "10ATM",
    features: ["gps", "ecg", "spo2", "music", "lte", "payments", "amoled", "swim"],
    bestFor: ["multisport", "outdoor", "running"],
    phones: ["android"],
    style: ["rugged", "sporty"],
    highlight: "Samsung's adventure flagship — titanium case, 100m water resistance, dual-frequency GPS.",
    asin: "B0D7F1LS4Q",
    reviewPath: "review/galaxy-watch-ultra",
    imageURL: "https://m.media-amazon.com/images/I/81yuteoAxNL._AC_SL1500_.jpg"
  },
  {
    id: "google-pixel-watch-3",
    brand: "Google",
    model: "Pixel Watch 3",
    year: 2024,
    category: "smartwatch",
    priceUSD: 349,
    batteryDays: 1,
    caseSizeMM: 45,
    weightGrams: 37,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "ecg", "spo2", "music", "payments", "amoled", "swim"],
    bestFor: ["everyday", "health", "running"],
    phones: ["android"],
    style: ["minimal", "luxury"],
    highlight: "Google's most refined Pixel Watch — Fitbit-powered fitness, gorgeous 320 ppi AMOLED.",
    asin: "B0D91268TH",
    reviewPath: "review/pixel-watch-3",
    imageURL: "https://m.media-amazon.com/images/I/61-JMO7a6%2BL._AC_SL1500_.jpg"
  },
  {
    id: "garmin-fenix-8",
    brand: "Garmin",
    model: "fēnix 8",
    year: 2024,
    category: "sportwatch",
    priceUSD: 1099,
    batteryDays: 16,
    caseSizeMM: 47,
    weightGrams: 73,
    display: "AMOLED",
    waterRating: "10ATM",
    features: ["gps", "spo2", "music", "payments", "amoled", "maps", "swim"],
    bestFor: ["multisport", "outdoor", "running"],
    phones: ["both"],
    style: ["rugged", "luxury"],
    highlight: "Garmin's no-compromise multisport flagship — built-in dive computer, AMOLED, multi-band GPS.",
    asin: "B0DD5S66GR",
    reviewPath: "review/garmin-fenix-8",
    imageURL: "https://m.media-amazon.com/images/I/617Rv1XcTnL._AC_SL1500_.jpg"
  },
  {
    id: "garmin-forerunner-965",
    brand: "Garmin",
    model: "Forerunner 965",
    year: 2023,
    category: "sportwatch",
    priceUSD: 599,
    batteryDays: 23,
    caseSizeMM: 47,
    weightGrams: 53,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "spo2", "music", "payments", "amoled", "maps", "swim"],
    bestFor: ["running", "multisport"],
    phones: ["both"],
    style: ["sporty"],
    highlight: "Best AMOLED running watch — full-color maps, training readiness and 23-day everyday battery.",
    asin: "B0BS1XZY7T",
    reviewPath: "review/garmin-forerunner-965-review",
    imageURL: "https://m.media-amazon.com/images/I/61H3akJEMML._AC_SL1500_.jpg"
  },
  {
    id: "garmin-forerunner-265",
    brand: "Garmin",
    model: "Forerunner 265",
    year: 2023,
    category: "sportwatch",
    priceUSD: 449,
    batteryDays: 13,
    caseSizeMM: 46,
    weightGrams: 47,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "spo2", "music", "amoled", "swim"],
    bestFor: ["running", "multisport"],
    phones: ["both"],
    style: ["sporty", "minimal"],
    highlight: "Mid-range runner's pick — bright AMOLED, training load focus, race predictor.",
    asin: "B0BS1T7G8S",
    imageURL: "https://m.media-amazon.com/images/I/71iSHugswGL._AC_SL1500_.jpg"
  },
  {
    id: "garmin-instinct-3",
    brand: "Garmin",
    model: "Instinct 3 Solar",
    year: 2025,
    category: "sportwatch",
    priceUSD: 449,
    batteryDays: 24,
    caseSizeMM: 45,
    weightGrams: 58,
    display: "MIP",
    waterRating: "10ATM",
    features: ["gps", "spo2", "swim"],
    bestFor: ["outdoor", "multisport"],
    phones: ["both"],
    style: ["rugged"],
    highlight: "Solar-charged tank — months of battery, MIL-STD-810 toughness, brilliant always-on MIP screen.",
    asin: "B0DSG9VCRH",
    reviewPath: "review/garmin-instinct-3",
    imageURL: "https://m.media-amazon.com/images/I/61YWK9flgBL._AC_SL1500_.jpg"
  },
  {
    id: "garmin-vivoactive-5",
    brand: "Garmin",
    model: "vívoactive 5",
    year: 2023,
    category: "smartwatch",
    priceUSD: 299,
    batteryDays: 11,
    caseSizeMM: 42,
    weightGrams: 36,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "spo2", "music", "payments", "amoled", "swim"],
    bestFor: ["everyday", "gym", "running"],
    phones: ["both"],
    style: ["minimal", "sporty"],
    highlight: "Most accessible Garmin AMOLED — 11-day battery, sleep coach, gym workouts and music storage.",
    asin: "B0CG6NR413",
    imageURL: "https://m.media-amazon.com/images/I/61A4yOWzGBL._AC_SL1500_.jpg"
  },
  {
    id: "coros-pace-3",
    brand: "Coros",
    model: "Pace 3",
    year: 2023,
    category: "sportwatch",
    priceUSD: 229,
    batteryDays: 24,
    caseSizeMM: 42,
    weightGrams: 30,
    display: "MIP",
    waterRating: "5ATM",
    features: ["gps", "music"],
    bestFor: ["running", "multisport"],
    phones: ["both"],
    style: ["minimal", "sporty"],
    highlight: "Ultralight runner's bargain — dual-frequency GPS at 30g, 24-day battery, EvoLab analytics.",
    asin: "B0CFQQ9FDL",
    reviewPath: "review/coros-pace-3-review",
    imageURL: "https://m.media-amazon.com/images/I/61HE8zhwT7L._AC_SL1500_.jpg"
  },
  {
    id: "coros-vertix-2s",
    brand: "Coros",
    model: "Vertix 2S",
    year: 2024,
    category: "sportwatch",
    priceUSD: 699,
    batteryDays: 40,
    caseSizeMM: 50,
    weightGrams: 72,
    display: "MIP",
    waterRating: "10ATM",
    features: ["gps", "spo2", "music", "maps", "swim"],
    bestFor: ["outdoor", "multisport"],
    phones: ["both"],
    style: ["rugged"],
    highlight: "40-day adventure beast — offline global maps, dual-frequency GPS, titanium bezel.",
    asin: "B0D12865TW",
    imageURL: "https://m.media-amazon.com/images/I/61osqSpRCuL._AC_SL1500_.jpg"
  },
  {
    id: "polar-vantage-v3",
    brand: "Polar",
    model: "Vantage V3",
    year: 2023,
    category: "sportwatch",
    priceUSD: 599,
    batteryDays: 8,
    caseSizeMM: 47,
    weightGrams: 57,
    display: "AMOLED",
    waterRating: "10ATM",
    features: ["gps", "ecg", "spo2", "amoled", "maps", "swim"],
    bestFor: ["multisport", "running", "health"],
    phones: ["both"],
    style: ["sporty"],
    highlight: "Lab-grade biometrics — ECG, skin-temp, wrist-based hemoglobin, training readiness.",
    asin: "B0DB8ZBN46",
    imageURL: "https://m.media-amazon.com/images/I/51Cf-tSvxHL._AC_SL1500_.jpg"
  },
  {
    id: "suunto-race",
    brand: "Suunto",
    model: "Race",
    year: 2023,
    category: "sportwatch",
    priceUSD: 449,
    batteryDays: 12,
    caseSizeMM: 49,
    weightGrams: 69,
    display: "AMOLED",
    waterRating: "10ATM",
    features: ["gps", "spo2", "amoled", "maps", "swim"],
    bestFor: ["outdoor", "multisport", "running"],
    phones: ["both"],
    style: ["rugged", "sporty"],
    highlight: "Finnish-built dual-frequency GPS with offline maps — rotating crown UI feels great.",
    imageURL: "https://m.media-amazon.com/images/I/71ceqlfJBaL._AC_SL1500_.jpg"
  },
  {
    id: "suunto-vertical",
    brand: "Suunto",
    model: "Vertical",
    year: 2023,
    category: "sportwatch",
    priceUSD: 629,
    batteryDays: 30,
    caseSizeMM: 49,
    weightGrams: 74,
    display: "AMOLED",
    waterRating: "10ATM",
    features: ["gps", "spo2", "amoled", "maps", "swim"],
    bestFor: ["outdoor", "multisport", "running"],
    phones: ["both"],
    style: ["rugged", "sporty"],
    highlight: "Adventure-class Suunto — offline topo maps, dual-band GPS and up to 60-day solar battery.",
    asin: "B0C11JCHBX",
    imageURL: "https://m.media-amazon.com/images/I/71-clzLBKlL._AC_SL1500_.jpg"
  },
  {
    id: "garmin-enduro-3",
    brand: "Garmin",
    model: "Enduro 3",
    year: 2024,
    category: "sportwatch",
    priceUSD: 899,
    batteryDays: 36,
    caseSizeMM: 51,
    weightGrams: 63,
    display: "MIP",
    waterRating: "10ATM",
    features: ["gps", "spo2", "music", "maps", "swim"],
    bestFor: ["outdoor", "multisport", "running"],
    phones: ["both"],
    style: ["rugged", "sporty"],
    highlight: "Ultra-runner's solar-charged tank — up to 90-day battery, full-color maps and titanium bezel.",
    asin: "B0DD5N9G17",
    imageURL: "https://m.media-amazon.com/images/I/71UvX-zVsAL._AC_SL1500_.jpg"
  },
  {
    id: "garmin-lily-2-active",
    brand: "Garmin",
    model: "Lily 2 Active",
    year: 2024,
    category: "smartwatch",
    priceUSD: 299,
    batteryDays: 9,
    caseSizeMM: 38,
    weightGrams: 29,
    display: "LCD",
    waterRating: "5ATM",
    features: ["gps", "spo2", "swim"],
    bestFor: ["everyday", "gym", "health"],
    phones: ["both"],
    style: ["minimal", "luxury"],
    highlight: "Stylish small-wrist Garmin — built-in GPS, sleep coach and feminine patterned lens.",
    asin: "B0DGVV6T6H",
    imageURL: "https://m.media-amazon.com/images/I/513KovBBrXL._AC_SL1500_.jpg"
  },
  {
    id: "amazfit-t-rex-3",
    brand: "Amazfit",
    model: "T-Rex 3",
    year: 2024,
    category: "sportwatch",
    priceUSD: 279,
    batteryDays: 27,
    caseSizeMM: 48,
    weightGrams: 68,
    display: "AMOLED",
    waterRating: "10ATM",
    features: ["gps", "spo2", "music", "amoled", "maps", "swim"],
    bestFor: ["outdoor", "multisport"],
    phones: ["both"],
    style: ["rugged"],
    highlight: "Rugged AMOLED at half the price — dual-band GPS, offline maps, 27-day battery.",
    asin: "B0DCZ9PRCP",
    reviewPath: "review/amazfit-t-rex-3",
    imageURL: "https://m.media-amazon.com/images/I/71GtgMbKvKL._AC_SL1500_.jpg"
  },
  {
    id: "amazfit-bip-5",
    brand: "Amazfit",
    model: "Bip 5 Unity",
    year: 2024,
    category: "smartwatch",
    priceUSD: 99,
    batteryDays: 11,
    caseSizeMM: 46,
    weightGrams: 33,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "spo2", "amoled"],
    bestFor: ["everyday", "gym"],
    phones: ["both"],
    style: ["minimal", "sporty"],
    highlight: "Big AMOLED smartwatch under $100 — surprisingly capable for daily fitness tracking.",
    asin: "B0CZP6V3MN",
    imageURL: "https://m.media-amazon.com/images/I/61kCGyZra5L._AC_SL1500_.jpg"
  },
  {
    id: "fitbit-charge-6",
    brand: "Fitbit",
    model: "Charge 6",
    year: 2023,
    category: "band",
    priceUSD: 159,
    batteryDays: 7,
    caseSizeMM: 36,
    weightGrams: 23,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "ecg", "spo2", "payments", "amoled", "swim"],
    bestFor: ["everyday", "health", "gym"],
    phones: ["both"],
    style: ["minimal"],
    highlight: "The most full-featured fitness band — built-in GPS, ECG and Google Maps on the wrist.",
    asin: "B0CHN2F11G",
    imageURL: "https://m.media-amazon.com/images/I/619Rq2X78zL._AC_SL1500_.jpg"
  },
  {
    id: "fitbit-inspire-3",
    brand: "Fitbit",
    model: "Inspire 3",
    year: 2022,
    category: "band",
    priceUSD: 99,
    batteryDays: 10,
    caseSizeMM: 35,
    weightGrams: 19,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["spo2", "amoled"],
    bestFor: ["everyday", "health"],
    phones: ["both"],
    style: ["minimal"],
    highlight: "Featherlight wellness band — sleep score, stress and active zone minutes.",
    asin: "B0B5F9SZW7",
    imageURL: "https://m.media-amazon.com/images/I/51CtR%2BquteL._AC_SL1500_.jpg"
  },
  {
    id: "fitbit-air",
    brand: "Fitbit",
    model: "Air",
    year: 2025,
    category: "band",
    priceUSD: 129,
    batteryDays: 10,
    caseSizeMM: 36,
    weightGrams: 22,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["spo2", "amoled"],
    bestFor: ["everyday", "health"],
    phones: ["both"],
    style: ["minimal"],
    highlight: "Fitbit's newest lightweight band — focused wellness tracking with a crisp AMOLED display.",
    asin: "B0GTMNC3YG",
    imageURL: "https://m.media-amazon.com/images/I/81jw3cF49lL._AC_SL1500_.jpg"
  },
  {
    id: "xiaomi-smart-band-9",
    brand: "Xiaomi",
    model: "Smart Band 9",
    year: 2024,
    category: "band",
    priceUSD: 49,
    batteryDays: 21,
    caseSizeMM: 47,
    weightGrams: 16,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["spo2", "amoled"],
    bestFor: ["everyday"],
    phones: ["both"],
    style: ["minimal"],
    highlight: "21-day battery in a $50 AMOLED band — unbeatable wellness tracker for the price.",
    asin: "B0D98HTWRR",
    imageURL: "https://m.media-amazon.com/images/I/61Yk24DAW7L._AC_SL1500_.jpg"
  },
  {
    id: "huawei-watch-gt-5-pro",
    brand: "Huawei",
    model: "Watch GT 5 Pro",
    year: 2024,
    category: "smartwatch",
    priceUSD: 379,
    batteryDays: 14,
    caseSizeMM: 46,
    weightGrams: 53,
    display: "AMOLED",
    waterRating: "10ATM",
    features: ["gps", "ecg", "spo2", "music", "amoled", "maps", "swim"],
    bestFor: ["everyday", "outdoor", "health"],
    phones: ["both"],
    style: ["luxury", "sporty"],
    highlight: "Two-week battery in a titanium-and-sapphire luxury smartwatch.",
    reviewPath: "review/huawei-watch-gt-5-pro",
    imageURL: "https://m.media-amazon.com/images/I/71dN-5SpyOL._AC_SL1500_.jpg"
  },
  {
    id: "withings-scanwatch-2",
    brand: "Withings",
    model: "ScanWatch 2",
    year: 2023,
    category: "hybrid",
    priceUSD: 349,
    batteryDays: 30,
    caseSizeMM: 42,
    weightGrams: 53,
    display: "OLED",
    waterRating: "5ATM",
    features: ["ecg", "spo2", "swim"],
    bestFor: ["health", "everyday"],
    phones: ["both"],
    style: ["luxury", "minimal"],
    highlight: "Analog hybrid with medical-grade ECG and 30-day battery — looks like a real watch.",
    imageURL: "https://m.media-amazon.com/images/I/61FooOnl3+L._AC_SL1500_.jpg"
  },
  {
    id: "whoop-4",
    brand: "Whoop",
    model: "4.0",
    year: 2023,
    category: "band",
    priceUSD: 239,
    batteryDays: 5,
    caseSizeMM: 32,
    weightGrams: 27,
    display: "E-ink",
    waterRating: "10ATM",
    features: ["spo2"],
    bestFor: ["health", "gym", "running"],
    phones: ["both"],
    style: ["minimal"],
    highlight: "Screen-free recovery and strain coaching — the choice of pro athletes (subscription required).",
    imageURL: "https://m.media-amazon.com/images/I/71CQ6esBqFL._AC_SL1500_.jpg"
  },
  {
    id: "mobvoi-ticwatch-pro-5",
    brand: "Mobvoi",
    model: "TicWatch Pro 5",
    year: 2023,
    category: "smartwatch",
    priceUSD: 349,
    batteryDays: 3,
    caseSizeMM: 50,
    weightGrams: 44,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "spo2", "payments", "amoled", "swim"],
    bestFor: ["everyday", "gym", "running"],
    phones: ["android"],
    style: ["sporty", "rugged"],
    highlight: "Dual-display Wear OS watch — premium chip and 80-hour standby thanks to its low-power overlay.",
    asin: "B0BYS4KJV6",
    imageURL: "https://m.media-amazon.com/images/I/71RTu5isl8L._AC_SL1500_.jpg"
  },
  {
    id: "apple-watch-series-11",
    brand: "Apple",
    model: "Watch Series 11",
    year: 2025,
    category: "smartwatch",
    priceUSD: 429,
    batteryDays: 1.5,
    caseSizeMM: 46,
    weightGrams: 36,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "ecg", "spo2", "music", "payments", "amoled", "swim"],
    bestFor: ["everyday", "health", "gym", "running"],
    phones: ["iphone"],
    style: ["minimal", "luxury", "sporty"],
    highlight: "The 2025 iPhone all-rounder — brighter always-on AMOLED, hypertension alerts, faster on-device Siri.",
    asin: "B0FQFJ4V5M",
    reviewPath: "review/apple-watch-series-11",
    imageURL: "https://m.media-amazon.com/images/I/61S%2B1BEQ8DL._AC_SL1500_.jpg"
  },
  {
    id: "apple-watch-ultra-3",
    brand: "Apple",
    model: "Watch Ultra 3",
    year: 2025,
    category: "smartwatch",
    priceUSD: 799,
    batteryDays: 1.7,
    caseSizeMM: 49,
    weightGrams: 61,
    display: "AMOLED",
    waterRating: "10ATM",
    features: ["gps", "ecg", "spo2", "music", "lte", "payments", "amoled", "maps", "swim"],
    bestFor: ["multisport", "outdoor", "running", "health"],
    phones: ["iphone"],
    style: ["rugged", "sporty", "luxury"],
    highlight: "Apple's 2025 adventure flagship — satellite messaging, 5G, and the longest-ever Apple Watch battery.",
    asin: "B0FQFHVZYL",
    reviewPath: "review/apple-watch-ultra-3",
    imageURL: "https://m.media-amazon.com/images/I/71pdSpwZJiL._AC_SL1500_.jpg"
  },
  {
    id: "apple-watch-se-3",
    brand: "Apple",
    model: "Watch SE 3",
    year: 2025,
    category: "smartwatch",
    priceUSD: 279,
    batteryDays: 1.3,
    caseSizeMM: 44,
    weightGrams: 33,
    display: "OLED",
    waterRating: "5ATM",
    features: ["gps", "music", "payments", "swim"],
    bestFor: ["everyday", "gym", "running"],
    phones: ["iphone"],
    style: ["minimal", "sporty"],
    highlight: "Refreshed budget Apple Watch — S10 chip, always-on display finally included.",
    asin: "B0FQFW7M9H",
    imageURL: "https://m.media-amazon.com/images/I/61ZTaGRrabL._AC_SL1500_.jpg"
  },
  {
    id: "samsung-galaxy-watch-8",
    brand: "Samsung",
    model: "Galaxy Watch 8",
    year: 2025,
    category: "smartwatch",
    priceUSD: 329,
    batteryDays: 1.7,
    caseSizeMM: 44,
    weightGrams: 34,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "ecg", "spo2", "music", "payments", "amoled", "swim"],
    bestFor: ["everyday", "health", "gym", "running"],
    phones: ["android"],
    style: ["minimal", "sporty"],
    highlight: "Galaxy AI on the wrist — antioxidant index, vascular load, brighter 3,000-nit AMOLED.",
    asin: "B0F7Q8BYJY",
    reviewPath: "review/samsung-galaxy-watch-8",
    imageURL: "https://m.media-amazon.com/images/I/616KEp7qQvL._AC_SL1500_.jpg"
  },
  {
    id: "samsung-galaxy-watch-8-classic",
    brand: "Samsung",
    model: "Galaxy Watch 8 Classic",
    year: 2025,
    category: "smartwatch",
    priceUSD: 499,
    batteryDays: 2,
    caseSizeMM: 46,
    weightGrams: 64,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "ecg", "spo2", "music", "payments", "amoled", "maps", "swim"],
    bestFor: ["everyday", "health", "running"],
    phones: ["android"],
    style: ["luxury", "minimal"],
    highlight: "Rotating bezel returns — premium stainless-steel Wear OS flagship with Galaxy AI coaching.",
    asin: "B0FNRY4F86",
    imageURL: "https://m.media-amazon.com/images/I/512qYFbL%2B9L._AC_SL1500_.jpg"
  },
  {
    id: "samsung-galaxy-watch-ultra-2025",
    brand: "Samsung",
    model: "Galaxy Watch Ultra (2025)",
    year: 2025,
    category: "smartwatch",
    priceUSD: 649,
    batteryDays: 2.7,
    caseSizeMM: 47,
    weightGrams: 60,
    display: "AMOLED",
    waterRating: "10ATM",
    features: ["gps", "ecg", "spo2", "music", "lte", "payments", "amoled", "maps", "swim"],
    bestFor: ["multisport", "outdoor", "running"],
    phones: ["android"],
    style: ["rugged", "sporty"],
    highlight: "Refined titanium adventure flagship — new Titanium Blue colorway and Galaxy AI workouts.",
    asin: "B0FJVKT38S",
    imageURL: "https://m.media-amazon.com/images/I/51mZspFnzjL._AC_SL1500_.jpg"
  },
  {
    id: "google-pixel-watch-4",
    brand: "Google",
    model: "Pixel Watch 4",
    year: 2025,
    category: "smartwatch",
    priceUSD: 379,
    batteryDays: 1.3,
    caseSizeMM: 45,
    weightGrams: 37,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "ecg", "spo2", "music", "payments", "amoled", "maps", "swim"],
    bestFor: ["everyday", "health", "running"],
    phones: ["android"],
    style: ["minimal", "luxury"],
    highlight: "Gemini-powered Pixel Watch — domed Actua 360 display, satellite SOS, repairable design.",
    asin: "B0FJWQP6LX",
    reviewPath: "review/pixel-watch-4",
    imageURL: "https://m.media-amazon.com/images/I/61EkR87Dp%2BL._AC_SL1500_.jpg"
  },
  {
    id: "garmin-forerunner-970",
    brand: "Garmin",
    model: "Forerunner 970",
    year: 2025,
    category: "sportwatch",
    priceUSD: 749,
    batteryDays: 15,
    caseSizeMM: 47,
    weightGrams: 56,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "ecg", "spo2", "music", "payments", "amoled", "maps", "swim"],
    bestFor: ["running", "multisport"],
    phones: ["both"],
    style: ["sporty", "luxury"],
    highlight: "Garmin's flagship runner — built-in LED flashlight, ECG, running tolerance and projected race time.",
    asin: "B0F8QYMD74",
    reviewPath: "review/garmin-forerunner-970",
    imageURL: "https://m.media-amazon.com/images/I/61pT16JQzzL._AC_SL1500_.jpg"
  },
  {
    id: "garmin-forerunner-570",
    brand: "Garmin",
    model: "Forerunner 570",
    year: 2025,
    category: "sportwatch",
    priceUSD: 549,
    batteryDays: 11,
    caseSizeMM: 47,
    weightGrams: 50,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "ecg", "spo2", "music", "payments", "amoled", "swim"],
    bestFor: ["running", "multisport"],
    phones: ["both"],
    style: ["sporty", "minimal"],
    highlight: "Mid-range runner reinvented — speaker, mic, ECG and dual-band GPS in a colorful aluminum case.",
    asin: "B0F8QYXTXH",
    imageURL: "https://m.media-amazon.com/images/I/61KpW67Q7dL._AC_SL1500_.jpg"
  },
  {
    id: "garmin-venu-4",
    brand: "Garmin",
    model: "Venu 4",
    year: 2025,
    category: "smartwatch",
    priceUSD: 549,
    batteryDays: 12,
    caseSizeMM: 45,
    weightGrams: 46,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "spo2", "music", "payments", "amoled", "swim"],
    bestFor: ["everyday", "health", "gym", "running"],
    phones: ["both"],
    style: ["minimal", "sporty"],
    highlight: "Lifestyle Garmin AMOLED — flashlight, refined sleep coach, and a polished everyday UI.",
    asin: "B0FRG18TLS",
    imageURL: "https://m.media-amazon.com/images/I/612juLR95TL._AC_SL1500_.jpg"
  },
  {
    id: "garmin-vivoactive-6",
    brand: "Garmin",
    model: "vívoactive 6",
    year: 2025,
    category: "smartwatch",
    priceUSD: 329,
    batteryDays: 11,
    caseSizeMM: 42,
    weightGrams: 36,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "spo2", "music", "payments", "amoled", "swim"],
    bestFor: ["everyday", "gym", "running"],
    phones: ["both"],
    style: ["minimal", "sporty"],
    highlight: "Most accessible Garmin AMOLED gets smarter — meditation, nap detection, suggested workouts.",
    asin: "B0F38GK1QZ",
    imageURL: "https://m.media-amazon.com/images/I/611jnYHa1OL._AC_SL1500_.jpg"
  },
  {
    id: "garmin-instinct-3-amoled",
    brand: "Garmin",
    model: "Instinct 3 AMOLED",
    year: 2025,
    category: "sportwatch",
    priceUSD: 499,
    batteryDays: 18,
    caseSizeMM: 45,
    weightGrams: 60,
    display: "AMOLED",
    waterRating: "10ATM",
    features: ["gps", "spo2", "swim"],
    bestFor: ["outdoor", "multisport"],
    phones: ["both"],
    style: ["rugged"],
    highlight: "First AMOLED Instinct — MIL-STD-810 toughness with a vivid color screen and built-in flashlight.",
    asin: "B0DSC8JF59",
    reviewPath: "review/garmin-instinct-3-amoled",
    imageURL: "https://m.media-amazon.com/images/I/61OQIbekPNL._AC_SL1500_.jpg"
  },
  {
    id: "amazfit-balance-2",
    brand: "Amazfit",
    model: "Balance 2",
    year: 2025,
    category: "smartwatch",
    priceUSD: 349,
    batteryDays: 21,
    caseSizeMM: 46,
    weightGrams: 40,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "ecg", "spo2", "music", "amoled", "maps", "swim"],
    bestFor: ["everyday", "health", "running"],
    phones: ["both"],
    style: ["minimal", "sporty"],
    highlight: "Wellness-first AMOLED — body composition, readiness score and offline maps for under $350.",
    asin: "B0F9JFCYNX",
    imageURL: "https://m.media-amazon.com/images/I/51p0LDEeINL._AC_SL1500_.jpg"
  },
  {
    id: "amazfit-t-rex-3-pro",
    brand: "Amazfit",
    model: "T-Rex 3 Pro",
    year: 2025,
    category: "sportwatch",
    priceUSD: 379,
    batteryDays: 25,
    caseSizeMM: 48,
    weightGrams: 70,
    display: "AMOLED",
    waterRating: "10ATM",
    features: ["gps", "spo2", "music", "amoled", "maps", "swim"],
    bestFor: ["outdoor", "multisport"],
    phones: ["both"],
    style: ["rugged"],
    highlight: "Rugged AMOLED upgraded — sapphire glass, brighter 3,000-nit screen and improved dual-band GPS.",
    asin: "B0FM2DDQ21",
    imageURL: "https://m.media-amazon.com/images/I/71udm2yMPRL._AC_SL1500_.jpg"
  },
  {
    id: "coros-pace-pro",
    brand: "Coros",
    model: "PACE Pro",
    year: 2024,
    category: "sportwatch",
    priceUSD: 349,
    batteryDays: 20,
    caseSizeMM: 46,
    weightGrams: 49,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "music", "amoled", "maps", "swim"],
    bestFor: ["running", "multisport"],
    phones: ["both"],
    style: ["sporty", "minimal"],
    highlight: "Coros goes AMOLED — offline maps, dual-frequency GPS and 20-day battery for serious runners.",
    asin: "B0DK31TB7G",
    reviewPath: "review/coros-pace-pro",
    imageURL: "https://m.media-amazon.com/images/I/612VXoI9XmL._AC_SL1500_.jpg"
  },
  // ──────────────────────────────────────────────────────────────────────────
  // Expanded 2023–2025 line-up. Entries below intentionally omit hard-coded
  // ASIN / imageURL — `amazonURL()` always builds tagged Amazon SEARCH URLs
  // (never a stale /dp/{ASIN} 404), and the SerpApi resolver in
  // amazon-product.functions.ts fetches the live first-result product image
  // at runtime. This guarantees correct affiliate attribution AND fresh,
  // matching product imagery without manual maintenance.
  // ──────────────────────────────────────────────────────────────────────────
  {
    id: "garmin-epix-pro-gen2-47",
    brand: "Garmin",
    model: "Epix Pro (Gen 2) 47mm",
    year: 2023,
    category: "sportwatch",
    priceUSD: 899,
    batteryDays: 16,
    caseSizeMM: 47,
    weightGrams: 70,
    display: "AMOLED",
    waterRating: "10ATM",
    features: ["gps", "spo2", "music", "payments", "amoled", "maps", "swim"],
    bestFor: ["multisport", "outdoor", "running"],
    phones: ["both"],
    style: ["rugged", "luxury", "sporty"],
    highlight: "AMOLED multisport flagship — built-in LED flashlight, full TopoActive maps, 16-day battery."
  },
  {
    id: "garmin-fenix-7-pro-sapphire-solar",
    brand: "Garmin",
    model: "fenix 7 Pro Sapphire Solar",
    year: 2023,
    category: "sportwatch",
    priceUSD: 899,
    batteryDays: 22,
    caseSizeMM: 47,
    weightGrams: 73,
    display: "MIP",
    waterRating: "10ATM",
    features: ["gps", "spo2", "music", "payments", "maps", "swim"],
    bestFor: ["multisport", "outdoor", "running"],
    phones: ["both"],
    style: ["rugged", "sporty"],
    highlight: "Solar-extended fenix — sapphire crystal, 22-day battery, full topo maps and built-in flashlight."
  },
  {
    id: "garmin-tactix-7-amoled",
    brand: "Garmin",
    model: "tactix 7 AMOLED Edition",
    year: 2023,
    category: "sportwatch",
    priceUSD: 1199,
    batteryDays: 11,
    caseSizeMM: 47,
    weightGrams: 89,
    display: "AMOLED",
    waterRating: "10ATM",
    features: ["gps", "spo2", "music", "payments", "amoled", "maps", "swim"],
    bestFor: ["outdoor", "multisport"],
    phones: ["both"],
    style: ["rugged"],
    highlight: "Tactical-grade fenix — night-vision compatibility, ballistics, jumpmaster, stealth GPS modes."
  },
  {
    id: "garmin-forerunner-165",
    brand: "Garmin",
    model: "Forerunner 165",
    year: 2024,
    category: "sportwatch",
    priceUSD: 249,
    batteryDays: 11,
    caseSizeMM: 43,
    weightGrams: 39,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "spo2", "amoled", "swim"],
    bestFor: ["running"],
    phones: ["both"],
    style: ["sporty", "minimal"],
    highlight: "Most affordable Garmin AMOLED runner — training readiness, race predictor and morning report."
  },
  {
    id: "garmin-forerunner-55",
    brand: "Garmin",
    model: "Forerunner 55",
    year: 2021,
    category: "sportwatch",
    priceUSD: 199,
    batteryDays: 14,
    caseSizeMM: 42,
    weightGrams: 37,
    display: "MIP",
    waterRating: "5ATM",
    features: ["gps"],
    bestFor: ["running"],
    phones: ["both"],
    style: ["minimal", "sporty"],
    highlight: "Beginner-friendly running GPS — coach-style plans, 14-day battery, refreshingly simple UI."
  },
  {
    id: "garmin-venu-sq-2",
    brand: "Garmin",
    model: "Venu Sq 2",
    year: 2022,
    category: "smartwatch",
    priceUSD: 249,
    batteryDays: 11,
    caseSizeMM: 40,
    weightGrams: 38,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "spo2", "music", "amoled"],
    bestFor: ["everyday", "gym", "running"],
    phones: ["both"],
    style: ["minimal", "sporty"],
    highlight: "Square-faced Apple Watch alternative for Android — 11-day battery, vivid AMOLED, on-watch music."
  },
  {
    id: "coros-apex-2-pro",
    brand: "Coros",
    model: "Apex 2 Pro",
    year: 2022,
    category: "sportwatch",
    priceUSD: 449,
    batteryDays: 30,
    caseSizeMM: 46,
    weightGrams: 53,
    display: "MIP",
    waterRating: "10ATM",
    features: ["gps", "spo2", "music", "maps", "swim"],
    bestFor: ["multisport", "outdoor", "running"],
    phones: ["both"],
    style: ["rugged", "sporty"],
    highlight: "Titanium dual-frequency GPS with offline global maps — 30-day battery for ultra athletes."
  },
  {
    id: "coros-pace-2",
    brand: "Coros",
    model: "PACE 2",
    year: 2020,
    category: "sportwatch",
    priceUSD: 199,
    batteryDays: 20,
    caseSizeMM: 42,
    weightGrams: 29,
    display: "MIP",
    waterRating: "5ATM",
    features: ["gps"],
    bestFor: ["running"],
    phones: ["both"],
    style: ["minimal", "sporty"],
    highlight: "29-gram running GPS for under $200 — long-standing budget favorite of marathoners."
  },
  {
    id: "polar-pacer-pro",
    brand: "Polar",
    model: "Pacer Pro",
    year: 2022,
    category: "sportwatch",
    priceUSD: 299,
    batteryDays: 7,
    caseSizeMM: 45,
    weightGrams: 41,
    display: "MIP",
    waterRating: "5ATM",
    features: ["gps"],
    bestFor: ["running"],
    phones: ["both"],
    style: ["sporty", "minimal"],
    highlight: "Lightweight running GPS with hill splitter, race pace and Polar's class-leading training load."
  },
  {
    id: "polar-grit-x2-pro",
    brand: "Polar",
    model: "Grit X2 Pro",
    year: 2024,
    category: "sportwatch",
    priceUSD: 749,
    batteryDays: 10,
    caseSizeMM: 47,
    weightGrams: 79,
    display: "AMOLED",
    waterRating: "10ATM",
    features: ["gps", "ecg", "spo2", "amoled", "maps", "swim"],
    bestFor: ["outdoor", "multisport", "running"],
    phones: ["both"],
    style: ["rugged", "sporty"],
    highlight: "Sapphire-glass adventure watch with full offline topo maps, ECG and MIL-STD-810H durability."
  },
  {
    id: "polar-ignite-3",
    brand: "Polar",
    model: "Ignite 3",
    year: 2022,
    category: "smartwatch",
    priceUSD: 329,
    batteryDays: 5,
    caseSizeMM: 43,
    weightGrams: 35,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "spo2", "amoled"],
    bestFor: ["everyday", "running", "health"],
    phones: ["both"],
    style: ["minimal", "sporty"],
    highlight: "Fitness watch with sleep-driven daily energy guidance and a vivid always-on AMOLED."
  },
  {
    id: "suunto-9-peak-pro",
    brand: "Suunto",
    model: "9 Peak Pro",
    year: 2022,
    category: "sportwatch",
    priceUSD: 549,
    batteryDays: 21,
    caseSizeMM: 43,
    weightGrams: 55,
    display: "MIP",
    waterRating: "10ATM",
    features: ["gps", "spo2", "maps", "swim"],
    bestFor: ["outdoor", "multisport", "running"],
    phones: ["both"],
    style: ["rugged", "minimal"],
    highlight: "Slim 10.8mm titanium adventurer — dual-band GPS, breadcrumb maps, 21-day smartwatch battery."
  },
  {
    id: "amazfit-gtr-4",
    brand: "Amazfit",
    model: "GTR 4",
    year: 2022,
    category: "smartwatch",
    priceUSD: 199,
    batteryDays: 14,
    caseSizeMM: 46,
    weightGrams: 34,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "spo2", "music", "amoled"],
    bestFor: ["everyday", "gym", "running"],
    phones: ["both"],
    style: ["luxury", "minimal", "sporty"],
    highlight: "Premium-feeling AMOLED smartwatch under $200 — dual-band GPS, Bluetooth calls, 14-day battery."
  },
  {
    id: "amazfit-active-2",
    brand: "Amazfit",
    model: "Active 2",
    year: 2025,
    category: "smartwatch",
    priceUSD: 99,
    batteryDays: 10,
    caseSizeMM: 43,
    weightGrams: 30,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "spo2", "amoled"],
    bestFor: ["everyday", "gym", "running"],
    phones: ["both"],
    style: ["minimal", "sporty"],
    highlight: "Sub-$100 AMOLED with stainless-steel bezel, dual-band GPS and Zepp Coach training plans."
  },
  {
    id: "amazfit-cheetah-pro",
    brand: "Amazfit",
    model: "Cheetah Pro",
    year: 2023,
    category: "sportwatch",
    priceUSD: 299,
    batteryDays: 14,
    caseSizeMM: 47,
    weightGrams: 43,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "spo2", "music", "amoled", "maps"],
    bestFor: ["running", "multisport"],
    phones: ["both"],
    style: ["sporty", "minimal"],
    highlight: "Lightweight running watch with dual-band GPS, on-device offline maps and AI-coached workouts."
  },
  {
    id: "oneplus-watch-3",
    brand: "OnePlus",
    model: "Watch 3",
    year: 2025,
    category: "smartwatch",
    priceUSD: 329,
    batteryDays: 5,
    caseSizeMM: 47,
    weightGrams: 49,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "ecg", "spo2", "music", "amoled", "swim"],
    bestFor: ["everyday", "health", "running"],
    phones: ["android"],
    style: ["sporty", "luxury"],
    highlight: "Wear OS 5 with Snapdragon W5 + BES2800 dual chips — 5-day smart battery and 16-day power-saver."
  },
  {
    id: "huawei-watch-ultimate",
    brand: "Huawei",
    model: "Watch Ultimate",
    year: 2023,
    category: "smartwatch",
    priceUSD: 899,
    batteryDays: 14,
    caseSizeMM: 49,
    weightGrams: 75,
    display: "AMOLED",
    waterRating: "10ATM",
    features: ["gps", "spo2", "music", "amoled", "maps", "swim"],
    bestFor: ["outdoor", "multisport"],
    phones: ["both"],
    style: ["luxury", "rugged"],
    highlight: "Zirconium-based liquid-metal dive watch — 110m depth rating, dual-band GPS, sapphire bezel."
  },
  {
    id: "huawei-watch-fit-3",
    brand: "Huawei",
    model: "Watch Fit 3",
    year: 2024,
    category: "band",
    priceUSD: 159,
    batteryDays: 10,
    caseSizeMM: 43,
    weightGrams: 26,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "spo2", "amoled"],
    bestFor: ["everyday", "gym"],
    phones: ["both"],
    style: ["minimal", "sporty"],
    highlight: "Apple-Watch-style aluminum chassis under $200 — 1.82\" AMOLED, GPS and 100+ workout modes."
  },
  {
    id: "xiaomi-watch-s3",
    brand: "Xiaomi",
    model: "Watch S3",
    year: 2024,
    category: "smartwatch",
    priceUSD: 149,
    batteryDays: 15,
    caseSizeMM: 47,
    weightGrams: 44,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "spo2", "amoled"],
    bestFor: ["everyday", "gym", "running"],
    phones: ["both"],
    style: ["minimal", "sporty"],
    highlight: "Swappable magnetic bezels, dual-band GPS and a 466×466 AMOLED for under $150."
  },
  {
    id: "fitbit-versa-4",
    brand: "Fitbit",
    model: "Versa 4",
    year: 2022,
    category: "smartwatch",
    priceUSD: 199,
    batteryDays: 6,
    caseSizeMM: 40,
    weightGrams: 38,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "spo2", "payments", "amoled", "swim"],
    bestFor: ["everyday", "gym", "running"],
    phones: ["both"],
    style: ["minimal", "sporty"],
    highlight: "Lightweight fitness smartwatch — built-in GPS, Google Maps + Wallet and Fitbit's renowned sleep score."
  },
  {
    id: "fitbit-sense-2",
    brand: "Fitbit",
    model: "Sense 2",
    year: 2022,
    category: "smartwatch",
    priceUSD: 249,
    batteryDays: 6,
    caseSizeMM: 41,
    weightGrams: 38,
    display: "AMOLED",
    waterRating: "5ATM",
    features: ["gps", "ecg", "spo2", "payments", "amoled", "swim"],
    bestFor: ["health", "everyday", "gym"],
    phones: ["both"],
    style: ["minimal"],
    highlight: "Continuous EDA stress sensor + ECG and skin-temperature tracking — Fitbit's most health-focused watch."
  },
  {
    id: "casio-gshock-gbd-h2000",
    brand: "Casio",
    model: "G-Shock GBD-H2000",
    year: 2023,
    category: "sportwatch",
    priceUSD: 399,
    batteryDays: 12,
    caseSizeMM: 52,
    weightGrams: 63,
    display: "MIP",
    waterRating: "20ATM",
    features: ["gps", "spo2"],
    bestFor: ["outdoor", "running", "multisport"],
    phones: ["both"],
    style: ["rugged", "sporty"],
    highlight: "True G-Shock toughness with GPS, optical HR and solar-assist charging — bombproof training partner."
  },
  {
    id: "withings-scanwatch-nova",
    brand: "Withings",
    model: "ScanWatch Nova",
    year: 2024,
    category: "hybrid",
    priceUSD: 599,
    batteryDays: 30,
    caseSizeMM: 42,
    weightGrams: 83,
    display: "OLED",
    waterRating: "10ATM",
    features: ["ecg", "spo2", "swim"],
    bestFor: ["health", "everyday"],
    phones: ["both"],
    style: ["luxury"],
    highlight: "Dive-styled luxury hybrid — sapphire crystal, ceramic bezel, FDA-cleared ECG and 30-day battery."
  },
  {
    id: "wahoo-elemnt-rival",
    brand: "Wahoo",
    model: "Elemnt Rival",
    year: 2020,
    category: "sportwatch",
    priceUSD: 379,
    batteryDays: 14,
    caseSizeMM: 46,
    weightGrams: 53,
    display: "MIP",
    waterRating: "5ATM",
    features: ["gps", "swim"],
    bestFor: ["multisport", "running"],
    phones: ["both"],
    style: ["sporty", "minimal"],
    highlight: "Triathlete's tool — touchless transition, multisport handoff to Wahoo bike computers, structured workouts."
  },
];

export function getWatchById(id: string): Watch | undefined {
  return watchDatabase.find((w) => w.id === id);
}

export const WATCH_DB_LAST_UPDATED = "May 2026";