/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as BrevoSmartwatchSequenceRouteImport } from './routes/brevo-smartwatch-sequence'
import { Route as BrevoRunningShoeSequenceRouteImport } from './routes/brevo-running-shoe-sequence'
import { Route as AffiliateDisclosureRouteImport } from './routes/affiliate-disclosure'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchSlugRouteImport } from './routes/watch.$slug'
import { Route as WatchMatchSlugRouteImport } from './routes/watch-match.$slug'
import { Route as CompareSlugRouteImport } from './routes/compare.$slug'
import { Route as ApiPublicVitalsRouteImport } from './routes/api/public/vitals'
import { Route as ApiPublicSubscribeRouteImport } from './routes/api/public/subscribe'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const BrevoSmartwatchSequenceRoute = BrevoSmartwatchSequenceRouteImport.update({
  id: '/brevo-smartwatch-sequence',
  path: '/brevo-smartwatch-sequence',
  getParentRoute: () => rootRouteImport,
} as any)
const BrevoRunningShoeSequenceRoute =
  BrevoRunningShoeSequenceRouteImport.update({
    id: '/brevo-running-shoe-sequence',
    path: '/brevo-running-shoe-sequence',
    getParentRoute: () => rootRouteImport,
  } as any)
const AffiliateDisclosureRoute = AffiliateDisclosureRouteImport.update({
  id: '/affiliate-disclosure',
  path: '/affiliate-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchSlugRoute = WatchSlugRouteImport.update({
  id: '/watch/$slug',
  path: '/watch/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchMatchSlugRoute = WatchMatchSlugRouteImport.update({
  id: '/watch-match/$slug',
  path: '/watch-match/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareSlugRoute = CompareSlugRouteImport.update({
  id: '/compare/$slug',
  path: '/compare/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVitalsRoute = ApiPublicVitalsRouteImport.update({
  id: '/api/public/vitals',
  path: '/api/public/vitals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSubscribeRoute = ApiPublicSubscribeRouteImport.update({
  id: '/api/public/subscribe',
  path: '/api/public/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/brevo-running-shoe-sequence': typeof BrevoRunningShoeSequenceRoute
  '/brevo-smartwatch-sequence': typeof BrevoSmartwatchSequenceRoute
  '/methodology': typeof MethodologyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/watch-match/$slug': typeof WatchMatchSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/api/public/subscribe': typeof ApiPublicSubscribeRoute
  '/api/public/vitals': typeof ApiPublicVitalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/brevo-running-shoe-sequence': typeof BrevoRunningShoeSequenceRoute
  '/brevo-smartwatch-sequence': typeof BrevoSmartwatchSequenceRoute
  '/methodology': typeof MethodologyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/watch-match/$slug': typeof WatchMatchSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/api/public/subscribe': typeof ApiPublicSubscribeRoute
  '/api/public/vitals': typeof ApiPublicVitalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/brevo-running-shoe-sequence': typeof BrevoRunningShoeSequenceRoute
  '/brevo-smartwatch-sequence': typeof BrevoSmartwatchSequenceRoute
  '/methodology': typeof MethodologyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/watch-match/$slug': typeof WatchMatchSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/api/public/subscribe': typeof ApiPublicSubscribeRoute
  '/api/public/vitals': typeof ApiPublicVitalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/brevo-running-shoe-sequence'
    | '/brevo-smartwatch-sequence'
    | '/methodology'
    | '/sitemap.xml'
    | '/compare/$slug'
    | '/watch-match/$slug'
    | '/watch/$slug'
    | '/api/public/subscribe'
    | '/api/public/vitals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/brevo-running-shoe-sequence'
    | '/brevo-smartwatch-sequence'
    | '/methodology'
    | '/sitemap.xml'
    | '/compare/$slug'
    | '/watch-match/$slug'
    | '/watch/$slug'
    | '/api/public/subscribe'
    | '/api/public/vitals'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/affiliate-disclosure'
    | '/brevo-running-shoe-sequence'
    | '/brevo-smartwatch-sequence'
    | '/methodology'
    | '/sitemap.xml'
    | '/compare/$slug'
    | '/watch-match/$slug'
    | '/watch/$slug'
    | '/api/public/subscribe'
    | '/api/public/vitals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AffiliateDisclosureRoute: typeof AffiliateDisclosureRoute
  BrevoRunningShoeSequenceRoute: typeof BrevoRunningShoeSequenceRoute
  BrevoSmartwatchSequenceRoute: typeof BrevoSmartwatchSequenceRoute
  MethodologyRoute: typeof MethodologyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CompareSlugRoute: typeof CompareSlugRoute
  WatchMatchSlugRoute: typeof WatchMatchSlugRoute
  WatchSlugRoute: typeof WatchSlugRoute
  ApiPublicSubscribeRoute: typeof ApiPublicSubscribeRoute
  ApiPublicVitalsRoute: typeof ApiPublicVitalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brevo-smartwatch-sequence': {
      id: '/brevo-smartwatch-sequence'
      path: '/brevo-smartwatch-sequence'
      fullPath: '/brevo-smartwatch-sequence'
      preLoaderRoute: typeof BrevoSmartwatchSequenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brevo-running-shoe-sequence': {
      id: '/brevo-running-shoe-sequence'
      path: '/brevo-running-shoe-sequence'
      fullPath: '/brevo-running-shoe-sequence'
      preLoaderRoute: typeof BrevoRunningShoeSequenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-disclosure': {
      id: '/affiliate-disclosure'
      path: '/affiliate-disclosure'
      fullPath: '/affiliate-disclosure'
      preLoaderRoute: typeof AffiliateDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$slug': {
      id: '/watch/$slug'
      path: '/watch/$slug'
      fullPath: '/watch/$slug'
      preLoaderRoute: typeof WatchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch-match/$slug': {
      id: '/watch-match/$slug'
      path: '/watch-match/$slug'
      fullPath: '/watch-match/$slug'
      preLoaderRoute: typeof WatchMatchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$slug': {
      id: '/compare/$slug'
      path: '/compare/$slug'
      fullPath: '/compare/$slug'
      preLoaderRoute: typeof CompareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vitals': {
      id: '/api/public/vitals'
      path: '/api/public/vitals'
      fullPath: '/api/public/vitals'
      preLoaderRoute: typeof ApiPublicVitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/subscribe': {
      id: '/api/public/subscribe'
      path: '/api/public/subscribe'
      fullPath: '/api/public/subscribe'
      preLoaderRoute: typeof ApiPublicSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AffiliateDisclosureRoute: AffiliateDisclosureRoute,
  BrevoRunningShoeSequenceRoute: BrevoRunningShoeSequenceRoute,
  BrevoSmartwatchSequenceRoute: BrevoSmartwatchSequenceRoute,
  MethodologyRoute: MethodologyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CompareSlugRoute: CompareSlugRoute,
  WatchMatchSlugRoute: WatchMatchSlugRoute,
  WatchSlugRoute: WatchSlugRoute,
  ApiPublicSubscribeRoute: ApiPublicSubscribeRoute,
  ApiPublicVitalsRoute: ApiPublicVitalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
