/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BrevoRunningShoeSequenceRouteImport } from './routes/brevo-running-shoe-sequence'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchMatchSlugRouteImport } from './routes/watch-match.$slug'

const BrevoRunningShoeSequenceRoute =
  BrevoRunningShoeSequenceRouteImport.update({
    id: '/brevo-running-shoe-sequence',
    path: '/brevo-running-shoe-sequence',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchMatchSlugRoute = WatchMatchSlugRouteImport.update({
  id: '/watch-match/$slug',
  path: '/watch-match/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brevo-running-shoe-sequence': typeof BrevoRunningShoeSequenceRoute
  '/watch-match/$slug': typeof WatchMatchSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brevo-running-shoe-sequence': typeof BrevoRunningShoeSequenceRoute
  '/watch-match/$slug': typeof WatchMatchSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brevo-running-shoe-sequence': typeof BrevoRunningShoeSequenceRoute
  '/watch-match/$slug': typeof WatchMatchSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/brevo-running-shoe-sequence' | '/watch-match/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/brevo-running-shoe-sequence' | '/watch-match/$slug'
  id: '__root__' | '/' | '/brevo-running-shoe-sequence' | '/watch-match/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrevoRunningShoeSequenceRoute: typeof BrevoRunningShoeSequenceRoute
  WatchMatchSlugRoute: typeof WatchMatchSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/brevo-running-shoe-sequence': {
      id: '/brevo-running-shoe-sequence'
      path: '/brevo-running-shoe-sequence'
      fullPath: '/brevo-running-shoe-sequence'
      preLoaderRoute: typeof BrevoRunningShoeSequenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch-match/$slug': {
      id: '/watch-match/$slug'
      path: '/watch-match/$slug'
      fullPath: '/watch-match/$slug'
      preLoaderRoute: typeof WatchMatchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrevoRunningShoeSequenceRoute: BrevoRunningShoeSequenceRoute,
  WatchMatchSlugRoute: WatchMatchSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
